version: "3.9"

services:
    redis:
      image: redis:latest
      restart: always
      container_name: redis
      ports:
        - "6379:6379"
      command: redis-server --save 60 1 --loglevel warning

    backend:
        container_name: django-backend
        build: .      
        volumes:
            - ./core:/app
            - static_volume:/app/static
            - media_volume:/app/media
        expose:
            - "8000"        
        command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
        environment:
            - SECRET_KEY=test
            - DEBUG=False
        depends_on:
            - redis
    
    worker-celery:
        build: .
        volumes:
            - ./core:/app
        command: celery -A core worker --loglevel=info
        depends_on:
            - redis
            - backend

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        ports: 
        - "80:80"
        depends_on:
            - redis
            - backend
        volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/home/app/static
        - media_volume:/home/app/media

volumes:
  static_volume:
  media_volume: