version: "3.9"

services:
    backend:
        container_name: django-backend
        build: .
        
        volumes:
            - ./core:/app

        ports:
            - "8002:8000"
        
        command: python manage.py runserver 0.0.0.0:8000

        environment:
            - SECRET_KEY=test
            - DEBUG=True
        