# Generated by Django 5.2.2 on 2025-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verficated',
            field=models.BooleanField(default=False, verbose_name='تاییدشده'),
        ),
    ]
