# Generated by Django 5.2.2 on 2025-07-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_description_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="description",
        ),
    ]
