name: Django Advanced Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker Compose
      run: docker compose up -d
    - name: Wait for containers to be ready
      run: sleep 10
    - name: Run Testing 
      run: docker exec django-backend sh -c "flake8 && pytest ."
